# Etapa 1: build con Node
FROM node:22-bullseye AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Variables de entorno se pasan desde Dokploy
RUN npm run build

# Etapa 2: servir con Nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
