export { Pricing } from "./Pricing";
export { Home } from "./Home";
export { Cartera } from "./Cartera";
export { Watchlist } from "./Watchlist";
export { Contact } from "./Contact";
export { Account } from "./Account";
export { Legal } from "./Legal";
export { Crypto } from "./Crypto";
export { Landing } from "./Landing";
export { Home as DashboardHome } from "./Home";
